---
title: Quarto Touying Clean
subtitle: A Minimalistic Theme for Quarto + Typst + Touying
date: today
date-format: long
author:
  - name: Kazuharu Yanagimoto
    orcid: 0009-0007-1967-8304
    email: kazuharu.yanagimoto@cemfi.edu.es
    affiliations: CEMFI
format:
  cleantouying-typst:
    keep-typ: true
    mainfont: Montserrat
    sansfont: Josefin Sans
    accent: 009F8C
    accent2: B75C9D
    bibliographystyle: "chicago-author-date"
bibliography: [references.bib]
---

## Example Slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.


# Components {background-color="#40666e"}

## Components

### Ordered & Unordered Lists

Here we have an unordered list.

- first item
    - sub-item
- second item

And next we have an ordered one.

1. first item
    1. sub-item
1. second item

## Components

### Alerts & Cross-refs {#sec-crossref}

To emphasize specific words or text, you can:

- Use the default `.alert` class, e.g. [important note]{.alert}
- Use the `.fg` class for custom color, e.g. [important note]{.fg}
- Use the `.bg` class for custom background, e.g. [important note]{.bg}

To cross-reference, you have several options, for example:

- Beamer-like .button class provided by this theme, e.g. [[Appendix]{.button}](#appendix)
- However, the heading cross-refs is not supported, see [Appendix](#appendix)

## Components

### Citations

Citations follow the standard
[Quarto format](https://quarto.org/docs/authoring/footnotes-and-citations.html#citations)
and be sourced from BibLaTeX, BibTeX, or CLS files. For example:

 - [Topic 1:]{.alert} Spatial Frictions [@Fajgelbaum_Morales_Serrato_Zidar_2018; @Hsieh_Moretti_2019; @Moretti_2011]

- [Topic 2:]{.alert} Blah [@Suárez_Serrato_Zidar_2016]

## Components

### Blocks

Quarto provides
[dedicated environments](https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs)
for theorems, lemmas, and so forth. 

But in presentation format, it's arguably more effective just to use a
[Callout Block](https://quarto.org/docs/authoring/callouts.html).


:::{.callout-note}
## Regression Specification

The main specification is as follows:

$$
y_{it} = X_{it} \beta + \mu_i + \varepsilon_{it}
$$
:::



# Appendix


## Touying Heading Cross-refs

[[Back to main]{.button}](#sec-crossref)
[appendix]{.label}

## References

::: {#refs}
:::
